# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disa_app', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
