# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disa_app', '0005_auto_20200226_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_doc',
            field=models.BooleanField(default=False),
        ),
    ]
