# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disa_app', '0007_markedfordeletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedfordeletion',
            name='doc_uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
