# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disa_app', '0008_auto_20200529_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markedfordeletion',
            old_name='json_data',
            new_name='doc_json_data',
        ),
        migrations.AddField(
            model_name='markedfordeletion',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedfordeletion',
            name='patron_json_data',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markedfordeletion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
