# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disa_app', '0009_auto_20200603_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedfordeletion',
            name='doc_json_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='markedfordeletion',
            name='patron_json_data',
            field=models.TextField(default='{}'),
        ),
    ]
